FROM node:23.3.0-bookworm AS build

RUN mkdir /app

COPY frontend /app/frontend

WORKDIR /app/frontend
RUN npm install
RUN npm run build

FROM nginx:1.27.3-alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html/app
COPY nginx.conf /etc/nginx/conf.d/default.conf
