apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    purpose: {{ .Release.Name }}-backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: {{ default "ClusterIP" .Values.backend.serviceType }}
  selector:
    purpose: {{ .Release.Name }}-backend